FROM debian:stable

WORKDIR /data

RUN apt-get update && apt-get install -y ffmpeg wget && \
	wget -O cqhttp.tar.gz  https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.0-rc3/go-cqhttp_linux_amd64.tar.gz  && \
	tar -zxvf cqhttp.tar.gz && mv ./go-cqhttp /usr/bin/go-cqhttp


ENTRYPOINT ["/usr/bin/go-cqhttp"]